name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn
                  cache-dependency-path: ./yarn.lock

            - name: Install dependencies
              run: yarn

            - name: Run Biome
              run: yarn biome ci

            - name: Build packages
              run: yarn packages:build
